name: Branch Protection Setup

on:
  workflow_dispatch: # Allow manual trigger

jobs:
  setup-protection:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup branch protection
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          
          try {
            await github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                checks: [
                  { context: 'coverage-summary' }
                ]
              },
              enforce_admins: false,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: false
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false,
              block_creations: false,
              required_conversation_resolution: true
            });
            
            console.log('✅ Branch protection rules updated successfully for main branch');
          } catch (error) {
            console.log('ℹ️ Branch protection update failed for main branch:', error.message);
            
            // Try master branch as fallback
            try {
              await github.rest.repos.updateBranchProtection({
                owner,
                repo,
                branch: 'master',
                required_status_checks: {
                  strict: true,
                  checks: [
                    { context: 'coverage-summary' }
                  ]
                },
                enforce_admins: false,
                required_pull_request_reviews: {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: false
                },
                restrictions: null,
                allow_force_pushes: false,
                allow_deletions: false,
                block_creations: false,
                required_conversation_resolution: true
              });
              
              console.log('✅ Branch protection rules updated successfully for master branch');
            } catch (masterError) {
              console.log('ℹ️ Branch protection update failed for master branch:', masterError.message);
              console.log('💡 Please manually configure branch protection rules in GitHub repository settings');
              console.log('Required status check: coverage-summary');
              console.log('Required: Pull request reviews (1), Dismiss stale reviews, Conversation resolution');
            }
          }