name: Generate Traceability Matrix

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  generate-traceability-matrix:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install cdlreq
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml jsonschema click openpyxl
        
        # Install cdlreq from GitHub
        git clone https://github.com/SeanHgh/cdlreq.git /tmp/cdlreq
        pip install -e /tmp/cdlreq

    - name: Generate traceability matrix using cdlreq export
      run: |
        echo "Generating traceability matrix..."
        cdlreq export --directory . --output requirements/traceability_matrix.xlsx
        
        # Also generate JSON format for easier inspection
        cdlreq export --directory . --output requirements/traceability_matrix.json --format json

    - name: Verify matrix files were created
      run: |
        echo "Generated files:"
        ls -la requirements/traceability_matrix*
        
        # Count requirements and specifications
        REQ_COUNT=$(find requirements -name "*.yaml" -not -path "*/specifications/*" | wc -l)
        SPEC_COUNT=$(find requirements/specifications -name "*.yaml" 2>/dev/null | wc -l || echo 0)
        
        echo "Matrix contains:"
        echo "- Requirements: $REQ_COUNT"
        echo "- Specifications: $SPEC_COUNT"

    - name: Commit traceability matrix
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add requirements/traceability_matrix.*
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update traceability matrix - Generated using cdlreq export and saved in requirements/ directory"
          git push

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: traceability-matrix
        path: requirements/traceability_matrix.*
        retention-days: 30